import { MetaTags } from "@xyd-js/core";

export const SUPPORTED_META_TAGS: MetaTags = {
    "robots": "name",
    "charset": "name",
    "viewport": "name",
    "description": "name",
    "keywords": "name",
    "author": "name",
    "googlebot": "name",
    "google": "name",
    "google-site-verification": "name",
    "generator": "name",
    "theme-color": "name",
    "color-scheme": "name",
    "format-detection": "name",
    "referrer": "name",
    "refresh": "name",
    "rating": "name",
    "revisit-after": "name",
    "language": "name",
    "copyright": "name",
    "reply-to": "name",
    "distribution": "name",
    "coverage": "name",
    "category": "name",
    "target": "name",
    "HandheldFriendly": "name",
    "MobileOptimized": "name",
    "apple-mobile-web-app-capable": "name",
    "apple-mobile-web-app-status-bar-style": "name",
    "apple-mobile-web-app-title": "name",
    "application-name": "name",
    "msapplication-TileColor": "name",
    "msapplication-TileImage": "name",
    "msapplication-config": "name",

    "og:title": "property",
    "og:type": "property",
    "og:url": "property",
    "og:image": "property",
    "og:description": "property",
    "og:site_name": "property",
    "og:locale": "property",
    "og:video": "property",
    "og:audio": "property",

    "twitter:card": "property",
    "twitter:site": "property",
    "twitter:creator": "property",
    "twitter:title": "property",
    "twitter:description": "property",
    "twitter:image": "property",
    "twitter:image:alt": "property",
    "twitter:player": "property",
    "twitter:player:width": "property",
    "twitter:player:height": "property",
    "twitter:app:name:iphone": "property",
    "twitter:app:id:iphone": "property",
    "twitter:app:url:iphone": "property",

    "article:published_time": "property",
    "article:modified_time": "property",
    "article:expiration_time": "property",
    "article:author": "property",
    "article:section": "property",
    "article:tag": "property",

    "book:author": "property",
    "book:isbn": "property",
    "book:release_date": "property",
    "book:tag": "property",

    "profile:first_name": "property",
    "profile:last_name": "property",
    "profile:username": "property",
    "profile:gender": "property",

    "music:duration": "property",
    "music:album": "property",
    "music:album:disc": "property",
    "music:album:track": "property",
    "music:musician": "property",
    "music:song": "property",
    "music:song:disc": "property",
    "music:song:track": "property",

    "video:actor": "property",
    "video:actor:role": "property",
    "video:director": "property",
    "video:writer": "property",
    "video:duration": "property",
    "video:release_date": "property",
    "video:tag": "property",
    "video:series": "property"
}